### ISSUE TITLE
footer breaking on downdetector.html

### ISSUE THREAD

**Issue by harrisemersyn** [rachael2016/UR-Web-Hub#11]

**Comment by SarahX** [comment]
the footer is now fixed on every page, and I reworked the headers to be out of layout so we can have custom titles and inline styles as necessary

the only issue is that the 24 outage reports section of downdetector.html is positioned incorrectly, I will try to fix this and then we should be all good

**Comment by SarahX** [comment]
height: 900px;  and float: left; in div.two messed up the footer but when I removed them the div.two is now positioned incorrectly

**Comment by harrisemersyn** [comment]
divs fixed through flex boxes and adjusting graph size via a JS script embedded in the HTML file, closing.
